[package]
name = "netconfig-backup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
csv = "1.2.1"
serde = {version = "1.0.158", features = ["derive"]}
ssh2 = "0.9.4"
